uint16 target1_x
uint16 target1_y

uint16 target2_x
uint16 target2_y

uint16 target3_x
uint16 target3_y

uint16 target4_x
uint16 target4_y

uint16 target5_x
uint16 target5_y

uint16 target6_x
uint16 target6_y

uint16 target7_x
uint16 target7_y

uint16 target8_x
uint16 target8_y

uint16 target9_x
uint16 target9_y

uint16 target10_x
uint16 target10_y

uint16 target11_x
uint16 target11_y

uint16 target12_x
uint16 target12_y

uint16 target13_x
uint16 target13_y

uint16 target14_x
uint16 target14_y

uint16 target15_x
uint16 target15_y

uint16 target16_x
uint16 target16_y

uint16 target17_x
uint16 target17_y

uint16 target18_x
uint16 target18_y

uint16 target19_x
uint16 target19_y

uint16 target20_x
uint16 target20_y

uint16 target21_x
uint16 target21_y

uint16 target22_x
uint16 target22_y

uint16 target23_x
uint16 target23_y

uint16 target24_x
uint16 target24_y

uint16 target25_x
uint16 target25_y

uint16 target26_x
uint16 target26_y

uint16 target27_x
uint16 target27_y

uint16 target28_x
uint16 target28_y

uint16 target29_x
uint16 target29_y

uint16 target30_x
uint16 target30_y

uint16 target31_x
uint16 target31_y

uint16 target32_x
uint16 target32_y

uint16 target33_x
uint16 target33_y

uint16 target34_x
uint16 target34_y

uint16 target35_x
uint16 target35_y

uint16 target36_x
uint16 target36_y

uint16 target37_x
uint16 target37_y

uint16 target38_x
uint16 target38_y

uint16 target39_x
uint16 target39_y

uint16 target40_x
uint16 target40_y

uint16 target41_x
uint16 target41_y

uint16 target42_x
uint16 target42_y

uint16 target43_x
uint16 target43_y

uint16 target44_x
uint16 target44_y

uint16 target45_x
uint16 target45_y

uint16 target46_x
uint16 target46_y

uint16 target47_x
uint16 target47_y

uint16 target48_x
uint16 target48_y

uint16 target49_x
uint16 target49_y

uint16 target50_x
uint16 target50_y